FROM arm64v8/alpine:3.11
LABEL image=ficoos/openvpn:arm64v8
ENV ARCH arm64v8
MAINTAINER Saggi Mizrahi "saggi@mizrahi.cc"

RUN apk update && \
    apk add openvpn tzdata

RUN adduser openvpn openvpn
ADD docker-entrypoint.sh /entrypoint.sh

VOLUME /config

ENTRYPOINT ["/entrypoint.sh"]
CMD [""]
